---

- name: install git
  apt: 
    name: git 
    state: latest

- name: create file for repo on Desktop
  file:
    path: /home/{{ ansible_user }}/Desktop/gitprojects
    state: directory

- name: GitCloneRepo
  ansible.builtin.git:
    repo: https://github.com/shannes01/vgpackagingVMutils.git
    dest: /home/{{ ansible_user }}/Desktop/gitprojects

...