---

- hosts: all
  become: true
  roles:
    - ListFiles
    - UpdateRepo

- hosts: webserver
  gather_facts: false
  become: true
  roles:
    - AddFilesFromGit
    
- hosts: webserver
  become: true
  roles:
    - AddBasicHTMLFolder
    - InstallApache

- hosts: loadbalancer
  become: true
  roles:
    - Installnginx

...